name: Publish to Pub.dev

on:
  # Runs on pushes targeting the default branch
#  push:
#    branches:
#      - main
#  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publishing:
    name: Publishing Job
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@main # required!

      - name: 'Publish Pub Package'
        uses: k-paxian/dart-package-publisher@master
        with:
          accessToken: ${{ secrets.PUB_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.PUB_REFRESH_TOKEN }}
          skipTests: true
          format: true